org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
# Proxy for dependency downloads (environment egress proxy)
systemProp.http.proxyHost=hatch-egress-proxy
systemProp.http.proxyPort=3128
systemProp.http.proxyUser=hatch-runtime
systemProp.http.proxyPassword=a9c2e806648348de8ff668d1e5582e33
systemProp.https.proxyHost=hatch-egress-proxy
systemProp.https.proxyPort=3128
systemProp.https.proxyUser=hatch-runtime
systemProp.https.proxyPassword=a9c2e806648348de8ff668d1e5582e33
systemProp.jdk.http.auth.tunneling.disabledSchemes=
